package wiregen_test

import (
	"os"
	"reflect"
	"strings"
	"testing"

	"github.com/cplieger/wiregen"
)

// =============================================================================
// Round 6: Post-refactor red-team
// Focus (a): NewRegistry(...Option) default parity with zero-value &Registry{}
// Focus (b): Re-attack prior surfaces + new refactor-exposed vectors
// =============================================================================

// --- FOCUS A: REFACTOR-SPECIFIC PROBES ---

// Test 1: NewRegistry() with no options produces IDENTICAL output as &Registry{}
// for the same payload. This is the core back-compat guarantee.
func TestR6_DefaultParity_NoOptions(t *testing.T) {
	payload := func(r *wiregen.Registry) {
		r.WireTypes = []reflect.Type{
			reflect.TypeFor[Address](),
			reflect.TypeFor[User](),
			reflect.TypeFor[Notification](),
		}
		r.Enums = map[string]wiregen.EnumDef{
			"Status": {Values: []string{"active", "inactive", "banned"}},
		}
		r.SSEEvents = []wiregen.SSERegEntry{
			{EventType: "notification", TypeName: "Notification"},
		}
		r.ValidatorsImport = "./v.js"
		r.BusImport = "./b.js"
	}

	// Zero-value registry
	zv := &wiregen.Registry{}
	payload(zv)

	// NewRegistry with no options
	nr := wiregen.NewRegistry()
	payload(nr)

	zvTypes := zv.GenerateTypes()
	nrTypes := nr.GenerateTypes()
	if zvTypes != nrTypes {
		t.Errorf("GenerateTypes differs between &Registry{} and NewRegistry():\n--- zero-value ---\n%s\n--- NewRegistry ---\n%s", zvTypes, nrTypes)
	}

	zvDec := zv.GenerateDecoders()
	nrDec := nr.GenerateDecoders()
	if zvDec != nrDec {
		t.Errorf("GenerateDecoders differs between &Registry{} and NewRegistry():\n--- zero-value ---\n%s\n--- NewRegistry ---\n%s", zvDec, nrDec)
	}

	zvReg := zv.GenerateRegistry()
	nrReg := nr.GenerateRegistry()
	if zvReg != nrReg {
		t.Errorf("GenerateRegistry differs between &Registry{} and NewRegistry():\n--- zero-value ---\n%s\n--- NewRegistry ---\n%s", zvReg, nrReg)
	}
}

// Test 2: Verify init() defaults match documentation expectations
func TestR6_InitDefaults(t *testing.T) {
	r := wiregen.NewRegistry()
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.ValidatorsImport = "./v.js"
	r.BusImport = "./b.js"
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "addr", TypeName: "Address"}}

	types := r.GenerateTypes()
	if !strings.HasPrefix(types, "// CODE-GENERATED by wiregen, DO NOT EDIT.\n\n") {
		t.Errorf("default HeaderComment not applied, got prefix: %q", types[:min(80, len(types))])
	}

	dec := r.GenerateDecoders()
	if !strings.Contains(dec, `from "./types.gen.js"`) {
		t.Errorf("default TypesImportPath not applied, got:\n%s", dec)
	}

	reg := r.GenerateRegistry()
	if !strings.Contains(reg, "registerSSEDecoder") {
		t.Errorf("default RegisterFuncName not applied, got:\n%s", reg)
	}
	if !strings.Contains(reg, "export function registerAllSSEDecoders()") {
		t.Errorf("default RegistryFuncName not applied, got:\n%s", reg)
	}
}

// Test 3: Each WithX knob takes effect independently
func TestR6_WithValidatorsImport(t *testing.T) {
	r := wiregen.NewRegistry(wiregen.WithValidatorsImport("@mylib/validate"))
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, `from "@mylib/validate"`) {
		t.Errorf("WithValidatorsImport not threaded, got:\n%s", dec)
	}
}

func TestR6_WithBusImport(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("@mylib/bus"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	reg := r.GenerateRegistry()
	if !strings.Contains(reg, `from "@mylib/bus"`) {
		t.Errorf("WithBusImport not threaded, got:\n%s", reg)
	}
}

func TestR6_WithTypesImportPath(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithTypesImportPath("../shared/types.js"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[User]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"a"}}}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, `from "../shared/types.js"`) {
		t.Errorf("WithTypesImportPath not threaded, got:\n%s", dec)
	}
}

func TestR6_WithHeaderComment(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithHeaderComment("/* GENERATED */\n\n"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	for _, out := range []string{r.GenerateTypes(), r.GenerateDecoders(), r.GenerateRegistry()} {
		if !strings.HasPrefix(out, "/* GENERATED */\n\n") {
			t.Errorf("WithHeaderComment not applied to all outputs, got prefix: %q", out[:min(40, len(out))])
		}
	}
}

func TestR6_WithRegisterFuncName(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithRegisterFuncName("customRegister"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	reg := r.GenerateRegistry()
	if !strings.Contains(reg, "customRegister") {
		t.Errorf("WithRegisterFuncName not threaded, got:\n%s", reg)
	}
}

func TestR6_WithRegistryFuncName(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithRegistryFuncName("initSSE"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	reg := r.GenerateRegistry()
	if !strings.Contains(reg, "export function initSSE()") {
		t.Errorf("WithRegistryFuncName not threaded, got:\n%s", reg)
	}
}

func TestR6_WithSelfContainedRegistry(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithSelfContainedRegistry(true),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	reg := r.GenerateRegistry()
	if !strings.Contains(reg, "new Map<string, Decoder<unknown>>()") {
		t.Errorf("WithSelfContainedRegistry(true) not threaded, got:\n%s", reg)
	}
}

func TestR6_WithFilenames(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithFilenames("t.ts", "d.ts", "r.ts", "c.ts"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	r.Constants = []wiregen.WireConst{{TSName: "X", Value: 1}}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	for _, f := range []string{"t.ts", "d.ts", "r.ts", "c.ts"} {
		if _, err := os.Stat(dir + "/" + f); err != nil {
			t.Errorf("expected file %s: %v", f, err)
		}
	}
}

// Test 4: WithFilenames with empty strings keeps defaults
func TestR6_WithFilenames_PartialEmpty(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithFilenames("custom_types.ts", "", "", ""),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	r.Constants = []wiregen.WireConst{{TSName: "X", Value: 1}}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	// custom_types.ts should exist (overridden)
	if _, err := os.Stat(dir + "/custom_types.ts"); err != nil {
		t.Errorf("expected custom_types.ts: %v", err)
	}
	// defaults for other files
	for _, f := range []string{"decoders.gen.ts", "registry.gen.ts", "constants.gen.ts"} {
		if _, err := os.Stat(dir + "/" + f); err != nil {
			t.Errorf("expected default file %s: %v", f, err)
		}
	}
}

// Test 5: Option order does NOT matter - applying in different order gives same result
func TestR6_OptionOrderIndependence(t *testing.T) {
	opts1 := []wiregen.Option{
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithTypesImportPath("./custom.js"),
		wiregen.WithHeaderComment("// H\n\n"),
		wiregen.WithRegisterFuncName("regFn"),
		wiregen.WithRegistryFuncName("allFn"),
		wiregen.WithSelfContainedRegistry(false),
	}
	opts2 := []wiregen.Option{
		wiregen.WithSelfContainedRegistry(false),
		wiregen.WithRegistryFuncName("allFn"),
		wiregen.WithRegisterFuncName("regFn"),
		wiregen.WithHeaderComment("// H\n\n"),
		wiregen.WithTypesImportPath("./custom.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithValidatorsImport("./v.js"),
	}

	setup := func(r *wiregen.Registry) {
		r.WireTypes = []reflect.Type{reflect.TypeFor[User](), reflect.TypeFor[Address]()}
		r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
		r.SSEEvents = []wiregen.SSERegEntry{{EventType: "u", TypeName: "User"}}
	}

	r1 := wiregen.NewRegistry(opts1...)
	setup(r1)
	r2 := wiregen.NewRegistry(opts2...)
	setup(r2)

	if r1.GenerateTypes() != r2.GenerateTypes() {
		t.Error("option order affected GenerateTypes")
	}
	if r1.GenerateDecoders() != r2.GenerateDecoders() {
		t.Error("option order affected GenerateDecoders")
	}
	if r1.GenerateRegistry() != r2.GenerateRegistry() {
		t.Error("option order affected GenerateRegistry")
	}
}

// Test 6: Later options override earlier ones (last-writer-wins)
func TestR6_OptionLastWriterWins(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithHeaderComment("// FIRST\n\n"),
		wiregen.WithHeaderComment("// SECOND\n\n"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.ValidatorsImport = "./v.js"
	out := r.GenerateTypes()
	if !strings.HasPrefix(out, "// SECOND\n\n") {
		t.Errorf("last-writer-wins not applied, got prefix: %q", out[:min(40, len(out))])
	}
}

// Test 7: nil Option in variadic doesn't panic
func TestR6_NilOptionNoPanic(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			t.Fatalf("nil option caused panic: %v", r)
		}
	}()
	// This tests that passing nil function doesn't panic
	var nilOpt wiregen.Option
	_ = wiregen.NewRegistry(nilOpt)
}

// Test 8: Options set via NewRegistry vs direct field assignment produce same output
func TestR6_OptionsVsDirectFields(t *testing.T) {
	// Via options
	rOpt := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithTypesImportPath("./t.js"),
		wiregen.WithHeaderComment("// H\n\n"),
		wiregen.WithRegisterFuncName("regFn"),
		wiregen.WithRegistryFuncName("allFn"),
		wiregen.WithSelfContainedRegistry(true),
	)
	rOpt.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	rOpt.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}

	// Via direct fields
	rDirect := &wiregen.Registry{
		ValidatorsImport:      "./v.js",
		BusImport:             "./b.js",
		TypesImportPath:       "./t.js",
		HeaderComment:         "// H\n\n",
		RegisterFuncName:      "regFn",
		RegistryFuncName:      "allFn",
		SelfContainedRegistry: true,
		WireTypes:             []reflect.Type{reflect.TypeFor[Address]()},
		SSEEvents:             []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}},
	}

	if rOpt.GenerateTypes() != rDirect.GenerateTypes() {
		t.Error("Options vs direct fields: GenerateTypes differs")
	}
	if rOpt.GenerateDecoders() != rDirect.GenerateDecoders() {
		t.Error("Options vs direct fields: GenerateDecoders differs")
	}
	if rOpt.GenerateRegistry() != rDirect.GenerateRegistry() {
		t.Error("Options vs direct fields: GenerateRegistry differs")
	}
}

// --- FOCUS B: RE-ATTACK + NEW VECTORS ---

// Test 9: isIdentReferenced empty-ident guard (regression check)
func TestR6_IsIdentReferencedEmptyGuard(t *testing.T) {
	// Type with empty tsName — the ident lookup must not infinite-loop
	type Inner struct {
		X string `json:"x"`
	}
	type Outer struct {
		I Inner `json:"i"`
	}
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[Inner](), reflect.TypeFor[Outer]()},
		TSNameOverride:   map[string]string{"Inner": ""},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	// Must complete without hang
	_ = r.GenerateDecoders()
}

// Test 10: Recursive self-embedding (ptr) — must not hang
func TestR6_RecursiveSelfEmbed(t *testing.T) {
	type Node struct {
		*Node
		V string `json:"v"`
	}
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[Node]()},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "v: string;") {
		t.Errorf("expected v field, got:\n%s", out)
	}
}

// Test 11: Mutual recursion A->B->A via ptr fields
func TestR6_MutualRecursionReattack(t *testing.T) {
	type A struct {
		B *struct {
			A *struct {
				X string `json:"x"`
			} `json:"a,omitempty"`
		} `json:"b,omitempty"`
		Name string `json:"name"`
	}
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[A]()},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "name: string;") {
		t.Errorf("expected name field, got:\n%s", out)
	}
}

// Test 12: Determinism - 300 iterations with options-created registry
func TestR6_DeterminismWithOptions(t *testing.T) {
	makeReg := func() *wiregen.Registry {
		r := wiregen.NewRegistry(
			wiregen.WithValidatorsImport("./v.js"),
			wiregen.WithBusImport("./b.js"),
			wiregen.WithHeaderComment("// H\n\n"),
			wiregen.WithTypesImportPath("./t.js"),
			wiregen.WithRegisterFuncName("reg"),
			wiregen.WithRegistryFuncName("all"),
		)
		r.WireTypes = []reflect.Type{
			reflect.TypeFor[Address](),
			reflect.TypeFor[User](),
			reflect.TypeFor[Notification](),
		}
		r.Enums = map[string]wiregen.EnumDef{
			"Status": {Values: []string{"active", "inactive"}},
		}
		r.SSEEvents = []wiregen.SSERegEntry{
			{EventType: "notif", TypeName: "Notification"},
			{EventType: "user", TypeName: "User"},
		}
		return r
	}

	ref := makeReg()
	typesRef := ref.GenerateTypes()
	decRef := ref.GenerateDecoders()
	regRef := ref.GenerateRegistry()

	for i := range 300 {
		r := makeReg()
		if r.GenerateTypes() != typesRef {
			t.Fatalf("iter %d: GenerateTypes differs", i)
		}
		if r.GenerateDecoders() != decRef {
			t.Fatalf("iter %d: GenerateDecoders differs", i)
		}
		if r.GenerateRegistry() != regRef {
			t.Fatalf("iter %d: GenerateRegistry differs", i)
		}
	}
}

// Test 13: Embedded ambiguity omission (regression)
func TestR6_EmbedAmbiguityRegression(t *testing.T) {
	type EA struct {
		F string `json:"f"`
	}
	type EB struct {
		F int `json:"f"`
	}
	host := reflect.StructOf([]reflect.StructField{
		{Name: "EA", Type: reflect.TypeFor[EA](), Anonymous: true},
		{Name: "EB", Type: reflect.TypeFor[EB](), Anonymous: true},
		{Name: "G", Type: reflect.TypeFor[string](), Tag: `json:"g"`},
	})
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{host},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if strings.Contains(out, "f:") || strings.Contains(out, "f?:") {
		t.Errorf("ambiguous field f should be omitted, got:\n%s", out)
	}
	if !strings.Contains(out, "g: string;") {
		t.Errorf("non-ambiguous field g missing, got:\n%s", out)
	}
}

// Test 14: Anonymous/empty-named reflect types don't panic
func TestR6_AnonymousReflectType(t *testing.T) {
	anon := reflect.StructOf([]reflect.StructField{
		{Name: "X", Type: reflect.TypeFor[int](), Tag: `json:"x"`},
	})
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{anon},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	// Must not panic or hang
	_ = r.GenerateTypes()
	_ = r.GenerateDecoders()
}

// Test 15: SelfContainedRegistry=false with empty BusImport panics correctly
func TestR6_SelfContainedFalseNoBusPanics(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithSelfContainedRegistry(false),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	defer func() {
		if rec := recover(); rec == nil {
			t.Fatal("expected panic with empty BusImport and SelfContainedRegistry=false")
		}
	}()
	r.GenerateRegistry()
}

// Test 16: WithSelfContainedRegistry(false) is same as default (false is zero)
func TestR6_SelfContainedFalseIsDefault(t *testing.T) {
	r1 := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r1.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r1.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}

	r2 := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithSelfContainedRegistry(false),
	)
	r2.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r2.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}

	if r1.GenerateRegistry() != r2.GenerateRegistry() {
		t.Error("WithSelfContainedRegistry(false) should match default")
	}
}
