package wiregen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cplieger/wiregen"
	"github.com/cplieger/wiregen/testdata/basic"
)

// validatorsContract is the exact set of names the validators starter MUST
// export: the 11 helper functions plus the Decoder<T> type alias. The
// generated decoders import a referenced subset of these by name, so the
// starter must export the full set for any generated import to resolve.
var validatorsContract = []string{
	"asObject", "asArray",
	"reqStr", "reqNum", "reqBool",
	"optStr", "optNum", "optBool",
	"reqOneOf",
	"decodeArray", "decodeRecord",
}

func validatorsRegistry() *wiregen.Registry {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithBusImport("./test-bus.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Address](),
		wiregen.TypeRef[basic.User](),
		wiregen.TypeRef[basic.Notification](),
	}
	r.Enums = map[string]wiregen.EnumDef{
		"Status": {Values: []string{"active", "inactive", "banned"}},
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	return r
}

// (a) The starter exports all 11 contract functions plus the Decoder<T> type.
func TestGenerateValidators_ExportsFullContract(t *testing.T) {
	out := wiregen.NewRegistry().GenerateValidators()

	for _, name := range validatorsContract {
		if !strings.Contains(out, "export function "+name+"(") &&
			!strings.Contains(out, "export function "+name+"<") {
			t.Errorf("validators starter missing exported function %q", name)
		}
	}

	if !strings.Contains(out, "export type Decoder<T> = (v: unknown) => T;") {
		t.Errorf("validators starter missing `export type Decoder<T> = (v: unknown) => T;`")
	}

	// reqOneOf must be generic over the enum value type.
	if !strings.Contains(out, "export function reqOneOf<T extends string>(") {
		t.Errorf("reqOneOf must be declared as `reqOneOf<T extends string>`")
	}
	// decodeArray / decodeRecord must be generic.
	if !strings.Contains(out, "export function decodeArray<T>(") {
		t.Errorf("decodeArray must be declared as `decodeArray<T>`")
	}
	if !strings.Contains(out, "export function decodeRecord<T>(") {
		t.Errorf("decodeRecord must be declared as `decodeRecord<T>`")
	}
}

// (b) The starter carries NO generated-file banner — it is consumer-owned.
func TestGenerateValidators_NoGeneratedBanner(t *testing.T) {
	out := wiregen.NewRegistry().GenerateValidators()

	for _, forbidden := range []string{"DO NOT EDIT", "CODE-GENERATED", "DO-NOT-EDIT"} {
		if strings.Contains(out, forbidden) {
			t.Errorf("validators starter must not contain %q (it is consumer-owned, not generated)", forbidden)
		}
	}

	// A custom HeaderComment must not leak into the starter either.
	r := wiregen.NewRegistry(wiregen.WithHeaderComment("// CODE-GENERATED by wiregen, DO NOT EDIT.\n\n"))
	if got := r.GenerateValidators(); strings.Contains(got, "DO NOT EDIT") || strings.Contains(got, "CODE-GENERATED") {
		t.Errorf("validators starter must not reuse r.HeaderComment")
	}

	// It should clearly mark itself as a copy-once, consumer-owned scaffold.
	if !strings.Contains(out, "copy") || !strings.Contains(strings.ToUpper(out), "OWN") {
		t.Errorf("validators starter banner should describe it as a copy-once, consumer-owned scaffold; got header:\n%s", firstLines(out, 4))
	}
	if !strings.Contains(out, "never regenerate") {
		t.Errorf("validators starter banner should state it is never regenerated")
	}
}

// (c) Default Generate(outDir) must NOT write a validators.ts file — an
// existing consumer's owned copy must never be clobbered.
func TestGenerate_DoesNotWriteValidators(t *testing.T) {
	dir := t.TempDir()
	r := validatorsRegistry()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}

	for _, e := range entries {
		name := strings.ToLower(e.Name())
		if strings.Contains(name, "validator") {
			t.Errorf("Generate wrote an unexpected validators file %q; the starter must be opt-in only", e.Name())
		}
	}

	// Belt-and-braces: the conventional filenames must be absent.
	for _, fn := range []string{"validators.ts", "validators.gen.ts"} {
		if _, err := os.Stat(filepath.Join(dir, fn)); !os.IsNotExist(err) {
			t.Errorf("Generate must not create %q (got stat err=%v)", fn, err)
		}
	}
}

// (d) The emitted helper names are a SUPERSET of the names a generated
// decoders.gen.ts imports, so any generated decoder import resolves against
// the starter.
func TestGenerateValidators_SupersetOfDecoderImports(t *testing.T) {
	r := validatorsRegistry()
	starter := r.GenerateValidators()
	decoders := r.GenerateDecoders()

	// Every contract helper referenced by the generated decoders must be
	// exported by the starter.
	for _, name := range validatorsContract {
		usedByDecoders := strings.Contains(decoders, name)
		exportedByStarter := strings.Contains(starter, "export function "+name)
		if usedByDecoders && !exportedByStarter {
			t.Errorf("generated decoders use helper %q but the starter does not export it", name)
		}
	}

	// And the starter is a strict superset: it exports all 11 regardless of
	// which subset the current decoders happen to reference.
	for _, name := range validatorsContract {
		if !strings.Contains(starter, "export function "+name) {
			t.Errorf("starter must export all 11 helpers; missing %q", name)
		}
	}
}

func firstLines(s string, n int) string {
	lines := strings.SplitN(s, "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}
