package wiregen_test

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cplieger/wiregen"
	"github.com/cplieger/wiregen/testdata/basic"
	"github.com/cplieger/wiregen/testdata/unions"
)

var update = flag.Bool("update", false, "update golden files")

// Ensure types are importable (compile-time check).
var (
	_ basic.User
	_ basic.Address
	_ basic.Notification
	_ basic.HasUnexported
	_ basic.HasBytes
	_ basic.HasOmitzero
	_ basic.HasJSONString
	_ basic.HasCustomMapped
	_ basic.HasTime
	_ basic.HasRaw
	_ basic.HasMap
	_ basic.HasInterface
	_ basic.WithEmbedding
	_ unions.CoverageEvent
	_ unions.NotifyEvent
	_ unions.ScanEvent
)

func newRegistry() *wiregen.Registry {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithBusImport("./test-bus.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Address](),
		wiregen.TypeRef[basic.User](),
		wiregen.TypeRef[basic.Notification](),
	}
	r.Enums = map[string]wiregen.EnumDef{
		"Status": {Values: []string{"active", "inactive", "banned"}},
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	return r
}

func TestGenerateTypes(t *testing.T) {
	r := newRegistry()
	out := r.GenerateTypes()

	if !strings.Contains(out, `export type Status = "active" | "inactive" | "banned";`) {
		t.Errorf("missing Status enum type, got:\n%s", out)
	}
	if !strings.Contains(out, "export interface User {") {
		t.Errorf("missing User interface, got:\n%s", out)
	}
	if !strings.Contains(out, "  id: number;") {
		t.Errorf("missing required id field, got:\n%s", out)
	}
	if !strings.Contains(out, "  email?: string;") {
		t.Errorf("missing optional email field, got:\n%s", out)
	}
	if !strings.Contains(out, "  address: Address;") {
		t.Errorf("missing nested struct field, got:\n%s", out)
	}
	if !strings.Contains(out, "  tags?: string[];") {
		t.Errorf("missing optional tags field, got:\n%s", out)
	}
	if !strings.Contains(out, "export interface Address {") {
		t.Errorf("missing Address interface, got:\n%s", out)
	}
}

func TestGenerateDecoders(t *testing.T) {
	r := newRegistry()
	out := r.GenerateDecoders()

	if !strings.Contains(out, "export const decodeUser: Decoder<User>") {
		t.Errorf("missing decodeUser, got:\n%s", out)
	}
	if !strings.Contains(out, "export const decodeAddress: Decoder<Address>") {
		t.Errorf("missing decodeAddress, got:\n%s", out)
	}
	if !strings.Contains(out, "reqOneOf(o, \"status\", STATUSS") {
		t.Errorf("missing enum validation for status, got:\n%s", out)
	}
	if !strings.Contains(out, "decodeAddress(o[\"address\"])") {
		t.Errorf("missing nested struct decoder call, got:\n%s", out)
	}
	if !strings.Contains(out, `from "./test-validators.js"`) {
		t.Errorf("missing validators import, got:\n%s", out)
	}
}

func TestGenerateRegistry(t *testing.T) {
	r := newRegistry()
	out := r.GenerateRegistry()

	if !strings.Contains(out, `registerSSEDecoder("notification", decodeNotification)`) {
		t.Errorf("missing SSE registration, got:\n%s", out)
	}
	if !strings.Contains(out, `from "./test-bus.js"`) {
		t.Errorf("missing bus import, got:\n%s", out)
	}
}

func TestGenerateToDir(t *testing.T) {
	r := newRegistry()
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	for _, f := range []string{"types.gen.ts", "decoders.gen.ts", "registry.gen.ts"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("expected file %s to exist: %v", f, err)
		}
	}
}

func TestGenerateConstants(t *testing.T) {
	r := &wiregen.Registry{
		Constants: []wiregen.WireConst{
			{TSName: "MSG_SCREEN", Value: 0},
			{TSName: "MSG_SCROLL", Value: 1},
			{TSName: "MODE_FLAG_BRACKETED_PASTE", Value: 0x01},
		},
	}
	out := r.GenerateConstants()

	if !strings.Contains(out, "// CODE-GENERATED by wiregen, DO NOT EDIT.") {
		t.Errorf("missing header comment, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MSG_SCREEN = 0;") {
		t.Errorf("missing MSG_SCREEN constant, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MSG_SCROLL = 1;") {
		t.Errorf("missing MSG_SCROLL constant, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MODE_FLAG_BRACKETED_PASTE = 1;") {
		t.Errorf("missing MODE_FLAG_BRACKETED_PASTE constant, got:\n%s", out)
	}
}

func TestGenerateConstants_Empty(t *testing.T) {
	r := newRegistry()
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	_, err := os.Stat(filepath.Join(dir, "constants.gen.ts"))
	if !os.IsNotExist(err) {
		t.Errorf("expected constants.gen.ts to not exist when Constants is empty, but it does")
	}
}

func TestGenerateRegistry_SelfContained(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithSelfContainedRegistry(true),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	out := r.GenerateRegistry()

	if !strings.Contains(out, "new Map<string, Decoder<unknown>>()") {
		t.Errorf("missing Map declaration, got:\n%s", out)
	}
	if !strings.Contains(out, "registry.set(") {
		t.Errorf("missing registry.set call, got:\n%s", out)
	}
	if !strings.Contains(out, "getSSEDecoder") {
		t.Errorf("missing getSSEDecoder function, got:\n%s", out)
	}
	if strings.Contains(out, "import { registerSSEDecoder }") {
		t.Errorf("should NOT contain registerSSEDecoder import in self-contained mode, got:\n%s", out)
	}
}

func TestGenerate_SelfContained_NoBusImport(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithSelfContainedRegistry(true),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate should succeed with SelfContainedRegistry=true and empty BusImport, got: %v", err)
	}
}

func TestPanicOnEmptyValidatorsImport(t *testing.T) {
	r := wiregen.NewRegistry()
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	defer func() {
		rec := recover()
		if rec == nil {
			t.Fatal("expected panic when ValidatorsImport is empty, but did not panic")
		}
		msg, ok := rec.(string)
		if !ok || !strings.Contains(msg, "ValidatorsImport must be set") {
			t.Fatalf("unexpected panic message: %v", rec)
		}
	}()
	r.GenerateDecoders()
}

func TestPanicOnEmptyBusImport(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	defer func() {
		rec := recover()
		if rec == nil {
			t.Fatal("expected panic when BusImport is empty, but did not panic")
		}
		msg, ok := rec.(string)
		if !ok || !strings.Contains(msg, "BusImport must be set") {
			t.Fatalf("unexpected panic message: %v", rec)
		}
	}()
	r.GenerateRegistry()
}

func TestUnexportedFieldsSkipped(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasUnexported]()}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  name: string;") {
		t.Errorf("exported field 'name' should be present, got:\n%s", out)
	}
	if strings.Contains(out, "internal") || strings.Contains(out, "hidden") {
		t.Errorf("unexported fields should NOT appear in output, got:\n%s", out)
	}
}

func TestByteSliceToString(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasBytes]()}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  data: string;") {
		t.Errorf("[]byte should map to string, got:\n%s", out)
	}
	if strings.Contains(out, "number[]") {
		t.Errorf("[]byte should NOT map to number[], got:\n%s", out)
	}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "reqStr(o, \"data\"") {
		t.Errorf("[]byte decoder should use reqStr, got:\n%s", dec)
	}
}

func TestOmitzeroMakesOptional(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasOmitzero]()}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  value?: string;") {
		t.Errorf("omitzero field should be optional, got:\n%s", out)
	}
	if !strings.Contains(out, "  name: string;") {
		t.Errorf("non-omitzero field should be required, got:\n%s", out)
	}
}

func TestJSONStringTag(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasJSONString]()}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  big_id: string;") {
		t.Errorf("json:\",string\" field should be typed as string, got:\n%s", out)
	}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "reqStr(o, \"big_id\"") {
		t.Errorf("json:\",string\" decoder should use reqStr, got:\n%s", dec)
	}
}

func TestDecoderMappings(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasCustomMapped]()}
	r.TypeMappings = map[string]string{
		"github.com/cplieger/wiregen/testdata/basic.CustomID": "string",
	}
	r.DecoderMappings = map[string]string{
		"github.com/cplieger/wiregen/testdata/basic.CustomID": "reqStr",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  id: string;") {
		t.Errorf("TypeMappings should map CustomID to string, got:\n%s", out)
	}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "reqStr(o, \"id\"") {
		t.Errorf("DecoderMappings should use reqStr for CustomID, got:\n%s", dec)
	}
}

func TestTypeMappingsWithoutDecoder(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasCustomMapped]()}
	r.TypeMappings = map[string]string{
		"github.com/cplieger/wiregen/testdata/basic.CustomID": "string",
	}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "o[\"id\"] as string") {
		t.Errorf("TypeMappings without DecoderMappings should cast, got:\n%s", dec)
	}
}

func TestTypesImportPath(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithTypesImportPath("../shared/types.gen.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.User]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, `from "../shared/types.gen.js"`) {
		t.Errorf("should use custom TypesImportPath, got:\n%s", dec)
	}
	if strings.Contains(dec, `from "./types.gen.js"`) {
		t.Errorf("should NOT use default types import path, got:\n%s", dec)
	}
}

func TestNewRegistry_Defaults(t *testing.T) {
	r := wiregen.NewRegistry()
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	out := r.GenerateTypes()
	if !strings.Contains(out, "// CODE-GENERATED by wiregen, DO NOT EDIT.") {
		t.Errorf("expected default header comment, got:\n%s", out)
	}
}

func TestNewRegistry_WithFilenames(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithFilenames("my_types.ts", "my_decoders.ts", "my_registry.ts", "my_consts.ts"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "addr", TypeName: "Address"}}
	r.Constants = []wiregen.WireConst{{TSName: "X", Value: 1}}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	for _, f := range []string{"my_types.ts", "my_decoders.ts", "my_registry.ts", "my_consts.ts"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("expected file %s to exist: %v", f, err)
		}
	}
}

func TestNewRegistry_WithRegistryFuncName(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithRegisterFuncName("myRegister"),
		wiregen.WithRegistryFuncName("initAll"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Notification]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "notif", TypeName: "Notification"}}
	out := r.GenerateRegistry()
	if !strings.Contains(out, "myRegister") {
		t.Errorf("expected custom register func name, got:\n%s", out)
	}
	if !strings.Contains(out, "export function initAll()") {
		t.Errorf("expected custom registry func name, got:\n%s", out)
	}
}

// --- Union tests ---

func TestUnionType(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/unions"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[unions.CoverageEvent](),
		wiregen.TypeRef[unions.NotifyEvent](),
		wiregen.TypeRef[unions.ScanEvent](),
	}
	// Register EventData as an interface type with union directive
	r.Types = append(r.Types, wiregen.WireType{
		PkgPath: "github.com/cplieger/wiregen/testdata/unions",
		Name:    "EventData",
	})
	r.DiscriminatorMap = map[string]map[string]string{
		"EventData": {
			"coverage":   "CoverageEvent",
			"notify":     "NotifyEvent",
			"scan:start": "ScanEvent",
			"scan:done":  "ScanEvent",
		},
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "export type EventData = CoverageEvent | NotifyEvent | ScanEvent;") {
		t.Errorf("missing union type, got:\n%s", out)
	}
	if !strings.Contains(out, "export interface CoverageEvent {") {
		t.Errorf("missing CoverageEvent interface, got:\n%s", out)
	}

	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "case \"coverage\": return decodeCoverageEvent(v);") {
		t.Errorf("missing union decoder case, got:\n%s", dec)
	}
	if !strings.Contains(dec, "case \"notify\": return decodeNotifyEvent(v);") {
		t.Errorf("missing notify case, got:\n%s", dec)
	}
}

// --- JSDoc/Comment tests ---

func TestJSDocPassthrough(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.User]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	out := r.GenerateTypes()
	if !strings.Contains(out, "/**") {
		t.Errorf("expected JSDoc comment in output, got:\n%s", out)
	}
}

// --- Determinism tests ---

func TestDeterministicOutput(t *testing.T) {
	for i := range 5 {
		r := newRegistry()
		out1 := r.GenerateTypes()
		r2 := newRegistry()
		out2 := r2.GenerateTypes()
		if out1 != out2 {
			t.Fatalf("non-deterministic output on run %d", i)
		}
	}
}

func TestDeterministicOutput_ShuffledRegistration(t *testing.T) {
	makeReg := func(types []wiregen.WireType) *wiregen.Registry {
		r := wiregen.NewRegistry(
			wiregen.WithValidatorsImport("./v.js"),
			wiregen.WithBusImport("./b.js"),
		)
		r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
		r.Types = types
		r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
		return r
	}

	order1 := []wiregen.WireType{
		wiregen.TypeRef[basic.User](),
		wiregen.TypeRef[basic.Address](),
		wiregen.TypeRef[basic.Notification](),
	}
	order2 := []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
		wiregen.TypeRef[basic.User](),
		wiregen.TypeRef[basic.Address](),
	}

	r1 := makeReg(order1)
	r2 := makeReg(order2)

	if r1.GenerateTypes() != r2.GenerateTypes() {
		t.Error("output differs with shuffled type registration order")
	}
}

// --- Golden file tests ---

func TestGolden_Types(t *testing.T) {
	r := newRegistry()
	r.Types = append(r.Types,
		wiregen.TypeRef[basic.HasTime](),
		wiregen.TypeRef[basic.HasBytes](),
		wiregen.TypeRef[basic.HasMap](),
		wiregen.TypeRef[basic.WithEmbedding](),
	)
	got := r.GenerateTypes()
	goldenCompare(t, "testdata/golden/types.gen.ts", got)
}

func TestGolden_Decoders(t *testing.T) {
	r := newRegistry()
	r.Types = append(r.Types,
		wiregen.TypeRef[basic.HasTime](),
		wiregen.TypeRef[basic.HasBytes](),
		wiregen.TypeRef[basic.HasMap](),
		wiregen.TypeRef[basic.WithEmbedding](),
	)
	got := r.GenerateDecoders()
	goldenCompare(t, "testdata/golden/decoders.gen.ts", got)
}

func goldenCompare(t *testing.T, path, got string) {
	t.Helper()
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("golden file %s not found (run with -update to create): %v", path, err)
	}
	if string(want) != got {
		t.Errorf("output differs from golden file %s.\nGot:\n%s\nWant:\n%s", path, got, string(want))
	}
}

// ExampleRegistry_Generate demonstrates basic wiregen usage.
func ExampleRegistry_Generate() {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./validators.js"),
		wiregen.WithBusImport("./bus.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Address](),
	}

	fmt.Println(r.GenerateTypes() != "")
	// Output:
	// true
}
