package wiregen_test

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cplieger/wiregen/v3"
	"github.com/cplieger/wiregen/v3/testdata/basic"
	"github.com/cplieger/wiregen/v3/testdata/unions"
)

var update = flag.Bool("update", false, "update golden files")

// Ensure types are importable (compile-time check).
var (
	_ basic.User
	_ basic.Address
	_ basic.Notification
	_ basic.HasUnexported
	_ basic.HasBytes
	_ basic.HasOmitzero
	_ basic.HasJSONString
	_ basic.HasCustomMapped
	_ basic.HasTime
	_ basic.HasRaw
	_ basic.HasMap
	_ basic.HasInterface
	_ basic.WithEmbedding
	_ unions.CoverageEvent
	_ unions.NotifyEvent
	_ unions.ScanEvent
)

func newRegistry() *wiregen.Registry {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithBusImport("./test-bus.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Address](),
		wiregen.TypeRef[basic.User](),
		wiregen.TypeRef[basic.Notification](),
	}
	r.Enums = map[string]wiregen.EnumDef{
		"Status": {Values: []string{"active", "inactive", "banned"}},
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	return r
}

func TestGenerateTypes(t *testing.T) {
	r := newRegistry()
	out := mustGen(t, r.GenerateTypes)

	if !strings.Contains(out, `export type Status = "active" | "inactive" | "banned";`) {
		t.Errorf("missing Status enum type, got:\n%s", out)
	}
	if !strings.Contains(out, "export interface User {") {
		t.Errorf("missing User interface, got:\n%s", out)
	}
	if !strings.Contains(out, "  id: number;") {
		t.Errorf("missing required id field, got:\n%s", out)
	}
	if !strings.Contains(out, "  email?: string;") {
		t.Errorf("missing optional email field, got:\n%s", out)
	}
	if !strings.Contains(out, "  address: Address;") {
		t.Errorf("missing nested struct field, got:\n%s", out)
	}
	if !strings.Contains(out, "  tags?: string[];") {
		t.Errorf("missing optional tags field, got:\n%s", out)
	}
	if !strings.Contains(out, "export interface Address {") {
		t.Errorf("missing Address interface, got:\n%s", out)
	}
}

func TestGenerateDecoders(t *testing.T) {
	r := newRegistry()
	out := mustGen(t, r.GenerateDecoders)

	if !strings.Contains(out, "export const decodeUser: Decoder<User>") {
		t.Errorf("missing decodeUser, got:\n%s", out)
	}
	if !strings.Contains(out, "export const decodeAddress: Decoder<Address>") {
		t.Errorf("missing decodeAddress, got:\n%s", out)
	}
	if !strings.Contains(out, "reqOneOf(o, \"status\", STATUSS") {
		t.Errorf("missing enum validation for status, got:\n%s", out)
	}
	if !strings.Contains(out, "decodeAddress(o[\"address\"])") {
		t.Errorf("missing nested struct decoder call, got:\n%s", out)
	}
	if !strings.Contains(out, `from "./test-validators.js"`) {
		t.Errorf("missing validators import, got:\n%s", out)
	}
}

func TestGenerateRegistry(t *testing.T) {
	r := newRegistry()
	out := mustGen(t, r.GenerateRegistry)

	if !strings.Contains(out, `registerSSEDecoder("notification", decodeNotification)`) {
		t.Errorf("missing SSE registration, got:\n%s", out)
	}
	if !strings.Contains(out, `from "./test-bus.js"`) {
		t.Errorf("missing bus import, got:\n%s", out)
	}
}

func TestGenerateToDir(t *testing.T) {
	r := newRegistry()
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	for _, f := range []string{"types.gen.ts", "decoders.gen.ts", "registry.gen.ts"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("expected file %s to exist: %v", f, err)
		}
	}
}

func TestGenerateConstants(t *testing.T) {
	r := &wiregen.Registry{
		Constants: []wiregen.WireConst{
			{TSName: "MSG_SCREEN", Value: 0},
			{TSName: "MSG_SCROLL", Value: 1},
			{TSName: "MODE_FLAG_BRACKETED_PASTE", Value: 0x01},
		},
	}
	out := mustGen(t, r.GenerateConstants)

	if !strings.Contains(out, "// CODE-GENERATED by wiregen, DO NOT EDIT.") {
		t.Errorf("missing header comment, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MSG_SCREEN = 0;") {
		t.Errorf("missing MSG_SCREEN constant, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MSG_SCROLL = 1;") {
		t.Errorf("missing MSG_SCROLL constant, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MODE_FLAG_BRACKETED_PASTE = 1;") {
		t.Errorf("missing MODE_FLAG_BRACKETED_PASTE constant, got:\n%s", out)
	}
}

func TestGenerateConstants_Empty(t *testing.T) {
	r := newRegistry()
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	_, err := os.Stat(filepath.Join(dir, "constants.gen.ts"))
	if !os.IsNotExist(err) {
		t.Errorf("expected constants.gen.ts to not exist when Constants is empty, but it does")
	}
}

func TestGenerateRegistry_SelfContained(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithSelfContainedRegistry(true),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	out := mustGen(t, r.GenerateRegistry)

	if !strings.Contains(out, "new Map<string, Decoder<unknown>>()") {
		t.Errorf("missing Map declaration, got:\n%s", out)
	}
	if !strings.Contains(out, "registry.set(") {
		t.Errorf("missing registry.set call, got:\n%s", out)
	}
	if !strings.Contains(out, "getSSEDecoder") {
		t.Errorf("missing getSSEDecoder function, got:\n%s", out)
	}
	if strings.Contains(out, "import { registerSSEDecoder }") {
		t.Errorf("should NOT contain registerSSEDecoder import in self-contained mode, got:\n%s", out)
	}
}

func TestGenerate_SelfContained_NoBusImport(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithSelfContainedRegistry(true),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate should succeed with SelfContainedRegistry=true and empty BusImport, got: %v", err)
	}
}

func TestErrorOnEmptyValidatorsImport(t *testing.T) {
	r := wiregen.NewRegistry()
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	_, err := r.GenerateDecoders()
	if err == nil {
		t.Fatal("expected error when ValidatorsImport is empty")
	}
	if !strings.Contains(err.Error(), "ValidatorsImport must be set") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestErrorOnEmptyBusImport(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	_, err := r.GenerateRegistry()
	if err == nil {
		t.Fatal("expected error when BusImport is empty")
	}
	if !strings.Contains(err.Error(), "BusImport must be set") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestUnexportedFieldsSkipped(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasUnexported]()}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "  name: string;") {
		t.Errorf("exported field 'name' should be present, got:\n%s", out)
	}
	if strings.Contains(out, "internal") || strings.Contains(out, "hidden") {
		t.Errorf("unexported fields should NOT appear in output, got:\n%s", out)
	}
}

func TestByteSliceToString(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasBytes]()}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "  data: string;") {
		t.Errorf("[]byte should map to string, got:\n%s", out)
	}
	if strings.Contains(out, "number[]") {
		t.Errorf("[]byte should NOT map to number[], got:\n%s", out)
	}
	dec := mustGen(t, r.GenerateDecoders)
	if !strings.Contains(dec, "reqStr(o, \"data\"") {
		t.Errorf("[]byte decoder should use reqStr, got:\n%s", dec)
	}
}

func TestOmitzeroMakesOptional(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasOmitzero]()}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "  value?: string;") {
		t.Errorf("omitzero field should be optional, got:\n%s", out)
	}
	if !strings.Contains(out, "  name: string;") {
		t.Errorf("non-omitzero field should be required, got:\n%s", out)
	}
}

func TestJSONStringTag(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasJSONString]()}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "  big_id: string;") {
		t.Errorf("json:\",string\" field should be typed as string, got:\n%s", out)
	}
	dec := mustGen(t, r.GenerateDecoders)
	if !strings.Contains(dec, "reqStr(o, \"big_id\"") {
		t.Errorf("json:\",string\" decoder should use reqStr, got:\n%s", dec)
	}
}

func TestDecoderMappings(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasCustomMapped]()}
	r.TypeMappings = map[string]string{
		"github.com/cplieger/wiregen/v3/testdata/basic.CustomID": "string",
	}
	r.DecoderMappings = map[string]string{
		"github.com/cplieger/wiregen/v3/testdata/basic.CustomID": "reqStr",
	}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "  id: string;") {
		t.Errorf("TypeMappings should map CustomID to string, got:\n%s", out)
	}
	dec := mustGen(t, r.GenerateDecoders)
	if !strings.Contains(dec, "reqStr(o, \"id\"") {
		t.Errorf("DecoderMappings should use reqStr for CustomID, got:\n%s", dec)
	}
}

// TestDecoderMappings_CollectionElement pins the mapped-element routing: a
// slice of a DecoderMappings-mapped type decodes per element through
// decodeArray — never as a whole-field scalar mapped call, which would hand
// the raw array to a scalar decoder — and the element decoder's synthesized
// single-key object carries the real wire name and type path so its error
// messages locate the actual field (the index prefix comes from decodeArray).
func TestDecoderMappings_CollectionElement(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasMappedSlice]()}
	r.TypeMappings = map[string]string{
		"github.com/cplieger/wiregen/v3/testdata/basic.CustomID": "string",
	}
	r.DecoderMappings = map[string]string{
		"github.com/cplieger/wiregen/v3/testdata/basic.CustomID": "reqStr",
	}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "  ids: string[];") {
		t.Errorf("mapped slice element should type as string[], got:\n%s", out)
	}
	dec := mustGen(t, r.GenerateDecoders)
	want := `ids: o["ids"] === null ? [] : decodeArray(o["ids"], (v) => reqStr({"ids": v} as Record<string, unknown>, "ids", "$.has_mapped_slice"), "$.has_mapped_slice.ids"),`
	if !strings.Contains(dec, want) {
		t.Errorf("mapped slice should decode per element, missing %q, got:\n%s", want, dec)
	}
	if strings.Contains(dec, `ids: reqStr(o, "ids"`) {
		t.Errorf("mapped slice must not decode as a whole-field scalar mapped call, got:\n%s", dec)
	}
}

func TestTypeMappingsWithoutDecoder(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.HasCustomMapped]()}
	r.TypeMappings = map[string]string{
		"github.com/cplieger/wiregen/v3/testdata/basic.CustomID": "string",
	}
	dec := mustGen(t, r.GenerateDecoders)
	if !strings.Contains(dec, "o[\"id\"] as string") {
		t.Errorf("TypeMappings without DecoderMappings should cast, got:\n%s", dec)
	}
}

func TestTypesImportPath(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithTypesImportPath("../shared/types.gen.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.User]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	dec := mustGen(t, r.GenerateDecoders)
	if !strings.Contains(dec, `from "../shared/types.gen.js"`) {
		t.Errorf("should use custom TypesImportPath, got:\n%s", dec)
	}
	if strings.Contains(dec, `from "./types.gen.js"`) {
		t.Errorf("should NOT use default types import path, got:\n%s", dec)
	}
}

func TestNewRegistry_Defaults(t *testing.T) {
	r := wiregen.NewRegistry()
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "// CODE-GENERATED by wiregen, DO NOT EDIT.") {
		t.Errorf("expected default header comment, got:\n%s", out)
	}
}

func TestNewRegistry_WithFilenames(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithFilenames(wiregen.Filenames{Types: "my_types.ts", Decoders: "my_decoders.ts", Registry: "my_registry.ts", Constants: "my_consts.ts"}),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "addr", TypeName: "Address"}}
	r.Constants = []wiregen.WireConst{{TSName: "X", Value: 1}}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	for _, f := range []string{"my_types.ts", "my_decoders.ts", "my_registry.ts", "my_consts.ts"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("expected file %s to exist: %v", f, err)
		}
	}
}

// TestWithFilenames_CrossImportsFollowTheNames pins the module specifiers the
// generated files use to import each OTHER against the renamed files. A
// renamed decoders file that the registry still imports as
// "./decoders.gen.js", or a renamed types file the decoders still import as
// "./types.gen.js", is a generated tree that does not resolve — the exact case
// WithFilenames exists for, and the case the file-existence checks above miss.
func TestWithFilenames_CrossImportsFollowTheNames(t *testing.T) {
	newReg := func(self bool) *wiregen.Registry {
		r := wiregen.NewRegistry(
			wiregen.WithValidatorsImport("./v.js"),
			wiregen.WithBusImport("./b.js"),
			wiregen.WithSelfContainedRegistry(self),
			wiregen.WithFilenames(wiregen.Filenames{Types: "my_types.ts", Decoders: "my_decoders.ts"}),
		)
		r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
		r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Notification]()}
		r.SSEEvents = []wiregen.SSERegEntry{{EventType: "notif", TypeName: "Notification"}}
		return r
	}
	for _, tc := range []struct {
		name string
		self bool
	}{{"busRegistry", false}, {"selfContainedRegistry", true}} {
		t.Run(tc.name, func(t *testing.T) {
			out := mustGen(t, newReg(tc.self).GenerateRegistry)
			if !strings.Contains(out, `from "./my_decoders.js"`) {
				t.Errorf("GenerateRegistry() = missing `from \"./my_decoders.js\"`, got:\n%s", out)
			}
			if strings.Contains(out, "decoders.gen.js") {
				t.Errorf("GenerateRegistry() = still names the default decoders module, got:\n%s", out)
			}
		})
	}
	t.Run("decodersImportTypes", func(t *testing.T) {
		out := mustGen(t, newReg(false).GenerateDecoders)
		if !strings.Contains(out, `from "./my_types.js"`) {
			t.Errorf("GenerateDecoders() = missing `from \"./my_types.js\"`, got:\n%s", out)
		}
		if strings.Contains(out, "types.gen.js") {
			t.Errorf("GenerateDecoders() = still names the default types module, got:\n%s", out)
		}
	})
	t.Run("explicitTypesImportPathWins", func(t *testing.T) {
		r := newReg(false)
		r.TypesImportPath = "../shared/types.js"
		out := mustGen(t, r.GenerateDecoders)
		if !strings.Contains(out, `from "../shared/types.js"`) {
			t.Errorf("GenerateDecoders() = explicit TypesImportPath ignored, got:\n%s", out)
		}
	})
}

// TestWithFilenames_ModuleSpecifierExtensions pins the source-to-module
// extension rewrite for the TypeScript extensions a consumer can legitimately
// use: .mts and .cts emit .mjs and .cjs, every other extension (and a name
// with none) emits .js.
func TestWithFilenames_ModuleSpecifierExtensions(t *testing.T) {
	for _, tc := range []struct{ decoders, want string }{
		{"my_decoders.ts", `from "./my_decoders.js"`},
		{"my_decoders.tsx", `from "./my_decoders.js"`},
		{"my_decoders.mts", `from "./my_decoders.mjs"`},
		{"my_decoders.cts", `from "./my_decoders.cjs"`},
		{"my_decoders", `from "./my_decoders.js"`},
	} {
		t.Run(tc.decoders, func(t *testing.T) {
			r := wiregen.NewRegistry(
				wiregen.WithValidatorsImport("./v.js"),
				wiregen.WithBusImport("./b.js"),
				wiregen.WithFilenames(wiregen.Filenames{Decoders: tc.decoders}),
			)
			r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
			r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Notification]()}
			r.SSEEvents = []wiregen.SSERegEntry{{EventType: "notif", TypeName: "Notification"}}
			out := mustGen(t, r.GenerateRegistry)
			if !strings.Contains(out, tc.want) {
				t.Errorf("GenerateRegistry() with Decoders=%q = missing %s, got:\n%s", tc.decoders, tc.want, out)
			}
		})
	}
}

func TestNewRegistry_WithRegistryFuncName(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithRegisterFuncName("myRegister"),
		wiregen.WithRegistryFuncName("initAll"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Notification]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "notif", TypeName: "Notification"}}
	out := mustGen(t, r.GenerateRegistry)
	if !strings.Contains(out, "myRegister") {
		t.Errorf("expected custom register func name, got:\n%s", out)
	}
	if !strings.Contains(out, "export function initAll()") {
		t.Errorf("expected custom registry func name, got:\n%s", out)
	}
}

func TestNewRegistry_FuncNameSanitized(t *testing.T) {
	// Non-identifier func-name knobs are sanitized to valid TS identifiers
	// (mirrors the other identifier knobs); valid names are byte-identical.
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithRegisterFuncName("2reg ister"),
		wiregen.WithRegistryFuncName("init All!"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Notification]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "notif", TypeName: "Notification"}}
	out := mustGen(t, r.GenerateRegistry)
	if !strings.Contains(out, "import { register }") || strings.Contains(out, "2reg ister") {
		t.Errorf("expected sanitized register func name 'register', got:\n%s", out)
	}
	if !strings.Contains(out, "export function initAll()") || strings.Contains(out, "init All!") {
		t.Errorf("expected sanitized registry func name 'initAll', got:\n%s", out)
	}
}

func TestNewRegistry_NilOptionsIgnored(t *testing.T) {
	r := wiregen.NewRegistry(nil, nil, wiregen.WithValidatorsImport("./v.js"), nil)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	if out := mustGen(t, r.GenerateTypes); out == "" {
		t.Error("nil options should be ignored and still generate output")
	}
}

func TestNewRegistry_OptionOrderIndependent(t *testing.T) {
	r1 := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithHeaderComment("// H\n\n"),
	)
	r2 := wiregen.NewRegistry(
		wiregen.WithHeaderComment("// H\n\n"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithValidatorsImport("./v.js"),
	)
	r1.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r2.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r1.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	r2.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	if mustGen(t, r1.GenerateTypes) != mustGen(t, r2.GenerateTypes) {
		t.Error("option order should not affect output")
	}
}

func TestNewRegistry_OptionLastWriterWins(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithHeaderComment("// first\n\n"),
		wiregen.WithHeaderComment("// second\n\n"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "// second") {
		t.Errorf("last writer should win, got:\n%s", out)
	}
}

func TestWithFilenames_EmptyKeepsDefaults(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithFilenames(wiregen.Filenames{}),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "Address"}}
	r.Constants = []wiregen.WireConst{{TSName: "X", Value: 1}}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatal(err)
	}
	// Empty filename args keep the defaults.
	for _, f := range []string{"types.gen.ts", "decoders.gen.ts", "registry.gen.ts", "constants.gen.ts"} {
		if _, err := os.Stat(filepath.Join(dir, f)); err != nil {
			t.Errorf("empty WithFilenames should keep default %s: %v", f, err)
		}
	}
}

func TestSelfContainedRegistry_EmptyValidatorsErrors(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithSelfContainedRegistry(true),
	)
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "a", TypeName: "X"}}
	if _, err := r.GenerateRegistry(); err == nil {
		t.Fatal("expected error")
	}
}

// --- JSDoc/Comment tests ---

func TestJSDocPassthrough(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{wiregen.TypeRef[basic.User]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	out := mustGen(t, r.GenerateTypes)
	if !strings.Contains(out, "/**") {
		t.Errorf("expected JSDoc comment in output, got:\n%s", out)
	}
}

// --- Golden file tests ---

func TestGolden_Types(t *testing.T) {
	r := newRegistry()
	r.Types = append(r.Types,
		wiregen.TypeRef[basic.HasTime](),
		wiregen.TypeRef[basic.HasBytes](),
		wiregen.TypeRef[basic.HasMap](),
		wiregen.TypeRef[basic.WithEmbedding](),
	)
	got := mustGen(t, r.GenerateTypes)
	goldenCompare(t, "testdata/golden/types.gen.ts", got)
}

func TestGolden_Decoders(t *testing.T) {
	r := newRegistry()
	r.Types = append(r.Types,
		wiregen.TypeRef[basic.HasTime](),
		wiregen.TypeRef[basic.HasBytes](),
		wiregen.TypeRef[basic.HasMap](),
		wiregen.TypeRef[basic.WithEmbedding](),
	)
	got := mustGen(t, r.GenerateDecoders)
	goldenCompare(t, "testdata/golden/decoders.gen.ts", got)
}

func goldenCompare(t *testing.T, path, got string) {
	t.Helper()
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("golden file %s not found (run with -update to create): %v", path, err)
	}
	if string(want) != got {
		t.Errorf("output differs from golden file %s.\nGot:\n%s\nWant:\n%s", path, got, string(want))
	}
}

// ExampleRegistry_Generate demonstrates basic wiregen usage.
func ExampleRegistry_Generate() {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./validators.js"),
		wiregen.WithBusImport("./bus.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{
		wiregen.TypeRef[basic.Address](),
	}

	ts, err := r.GenerateTypes()
	if err != nil {
		fmt.Println("generate:", err)
		return
	}
	fmt.Println(ts != "")
	// Output:
	// true
}

// --- TypeRef registration ---

func TestTypeRef(t *testing.T) {
	if wt := wiregen.TypeRef[basic.User](); wt.Name != "User" ||
		wt.PkgPath != "github.com/cplieger/wiregen/v3/testdata/basic" {
		t.Errorf("TypeRef[User]() = %+v, want {basic, User}", wt)
	}
	// A pointer type unwraps to its element.
	if wt := wiregen.TypeRef[*basic.Address](); wt.Name != "Address" {
		t.Errorf("TypeRef[*Address]().Name = %q, want %q", wt.Name, "Address")
	}
}

// --- Generate error paths ---

func TestGenerate_UnknownTypeErrors(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/cplieger/wiregen/v3/testdata/basic"}
	r.Types = []wiregen.WireType{
		{PkgPath: "github.com/cplieger/wiregen/v3/testdata/basic", Name: "NonExistentType"},
	}
	err := r.Generate(t.TempDir())
	if err == nil {
		t.Fatal("expected error when referencing non-existent type, got nil")
	}
	if !strings.Contains(err.Error(), "not found") {
		t.Errorf("expected 'not found' in error, got: %v", err)
	}
}

func TestGenerate_PackageLoadFailureErrors(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.PackagePaths = []string{"github.com/totally/nonexistent/package/path"}
	r.Types = []wiregen.WireType{
		{PkgPath: "github.com/totally/nonexistent/package/path", Name: "Foo"},
	}
	if err := r.Generate(t.TempDir()); err == nil {
		t.Fatal("expected error for non-existent package, got nil")
	}
}

// TestGenerate_RejectsUnsanitizableConstant pins the constants validation: a
// WireConst whose TSName sanitizes to an empty TS identifier is a Generate
// error (previously it was silently dropped from constants.gen.ts), and
// nothing is written.
func TestGenerate_RejectsUnsanitizableConstant(t *testing.T) {
	r := wiregen.NewRegistry(wiregen.WithValidatorsImport("./v.js"))
	r.Constants = []wiregen.WireConst{
		{TSName: "MaxRetries", Value: 3},
		{TSName: "404", Value: 5}, // digits only — sanitizes to ""
	}
	dir := t.TempDir()
	err := r.Generate(dir)
	if err == nil {
		t.Fatal("expected error for unsanitizable constant TSName, got nil")
	}
	if !strings.Contains(err.Error(), `"404"`) {
		t.Errorf("error should name the offending TSName, got: %v", err)
	}
	entries, readErr := os.ReadDir(dir)
	if readErr != nil {
		t.Fatalf("ReadDir: %v", readErr)
	}
	if len(entries) != 0 {
		t.Errorf("Generate must write nothing on a constants validation error, found %d entries", len(entries))
	}
}

// TestGenerateConstants_ErrorsOnUnsanitizableName pins the unified error
// model: the string getter returns the same config error Generate returns.
func TestGenerateConstants_ErrorsOnUnsanitizableName(t *testing.T) {
	r := wiregen.NewRegistry(wiregen.WithValidatorsImport("./v.js"))
	r.Constants = []wiregen.WireConst{{TSName: "!!!", Value: 1}} // no identifier-safe runes
	if _, err := r.GenerateConstants(); err == nil {
		t.Error("expected GenerateConstants to error on unsanitizable TSName")
	}
}

// --- empty / constants-only registries ---

func TestGenerate_EmptyRegistry(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	if err := r.Generate(t.TempDir()); err != nil {
		t.Fatalf("empty registry should generate fine, got: %v", err)
	}
}

func TestGenerate_ConstantsOnly(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
	)
	r.Constants = []wiregen.WireConst{
		{TSName: "FOO", Value: 42},
		{TSName: "BAR", Value: -1},
	}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatal(err)
	}
	content, err := os.ReadFile(filepath.Join(dir, "constants.gen.ts"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "export const FOO = 42;") {
		t.Errorf("missing FOO, got:\n%s", content)
	}
	if !strings.Contains(string(content), "export const BAR = -1;") {
		t.Errorf("missing BAR, got:\n%s", content)
	}
}
