package wiregen_test

import (
	"fmt"
	"os"
	"reflect"
	"strings"
	"testing"

	"github.com/cplieger/wiregen"
)

// Sample types for testing — these simulate what a consumer would register.

type Status string // enum

type Address struct {
	Street string `json:"street"`
	City   string `json:"city"`
	Zip    string `json:"zip,omitempty"`
}

type User struct {
	Age     *int     `json:"age,omitempty"`
	Address Address  `json:"address"`
	Name    string   `json:"name"`
	Email   string   `json:"email,omitempty"`
	Status  Status   `json:"status"`
	Tags    []string `json:"tags,omitempty"`
	ID      int      `json:"id"`
}

type Notification struct {
	Kind    string `json:"kind"`
	Message string `json:"message"`
}

// --- Types for new feature tests ---

// HasUnexported has unexported fields that must be skipped.
type HasUnexported struct {
	Name     string `json:"name"`
	internal int    //nolint:unused // intentionally unexported for test
	hidden   string //nolint:unused // intentionally unexported for test
}

// HasBytes has a []byte field that should map to string (base64).
type HasBytes struct {
	Data []byte `json:"data"`
	Name string `json:"name"`
}

// HasOmitzero uses the Go 1.24 omitzero tag option.
type HasOmitzero struct {
	Value string `json:"value,omitzero"`
	Name  string `json:"name"`
}

// HasJSONString uses json:",string" to wrap a number as string on the wire.
type HasJSONString struct {
	BigID int64  `json:"big_id,string"`
	Name  string `json:"name"`
}

// CustomID is a custom type for testing TypeMappings/DecoderMappings.
type CustomID struct{ Value string }

// HasCustomMapped uses a custom-mapped type.
type HasCustomMapped struct {
	ID   CustomID `json:"id"`
	Name string   `json:"name"`
}

func newRegistry() *wiregen.Registry {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithBusImport("./test-bus.js"),
	)
	r.WireTypes = []reflect.Type{
		reflect.TypeFor[Address](),
		reflect.TypeFor[User](),
		reflect.TypeFor[Notification](),
	}
	r.Enums = map[string]wiregen.EnumDef{
		"Status": {Values: []string{"active", "inactive", "banned"}},
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	return r
}

func TestGenerateTypes(t *testing.T) {
	r := newRegistry()
	out := r.GenerateTypes()

	// Check enum
	if !strings.Contains(out, `export type Status = "active" | "inactive" | "banned";`) {
		t.Errorf("missing Status enum type, got:\n%s", out)
	}
	// Check interface
	if !strings.Contains(out, "export interface User {") {
		t.Errorf("missing User interface, got:\n%s", out)
	}
	if !strings.Contains(out, "  id: number;") {
		t.Errorf("missing required id field, got:\n%s", out)
	}
	if !strings.Contains(out, "  email?: string;") {
		t.Errorf("missing optional email field, got:\n%s", out)
	}
	if !strings.Contains(out, "  address: Address;") {
		t.Errorf("missing nested struct field, got:\n%s", out)
	}
	if !strings.Contains(out, "  tags?: string[];") {
		t.Errorf("missing optional tags field, got:\n%s", out)
	}
	if !strings.Contains(out, "export interface Address {") {
		t.Errorf("missing Address interface, got:\n%s", out)
	}
}

func TestGenerateDecoders(t *testing.T) {
	r := newRegistry()
	out := r.GenerateDecoders()

	if !strings.Contains(out, "export const decodeUser: Decoder<User>") {
		t.Errorf("missing decodeUser, got:\n%s", out)
	}
	if !strings.Contains(out, "export const decodeAddress: Decoder<Address>") {
		t.Errorf("missing decodeAddress, got:\n%s", out)
	}
	if !strings.Contains(out, "reqOneOf(o, \"status\", STATUSS") {
		t.Errorf("missing enum validation for status, got:\n%s", out)
	}
	if !strings.Contains(out, "decodeAddress(o[\"address\"])") {
		t.Errorf("missing nested struct decoder call, got:\n%s", out)
	}
	// Check validators import
	if !strings.Contains(out, `from "./test-validators.js"`) {
		t.Errorf("missing validators import, got:\n%s", out)
	}
}

func TestGenerateRegistry(t *testing.T) {
	r := newRegistry()
	out := r.GenerateRegistry()

	if !strings.Contains(out, `registerSSEDecoder("notification", decodeNotification)`) {
		t.Errorf("missing SSE registration, got:\n%s", out)
	}
	if !strings.Contains(out, `from "./test-bus.js"`) {
		t.Errorf("missing bus import, got:\n%s", out)
	}
}

func TestGenerateToDir(t *testing.T) {
	r := newRegistry()
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
}

func TestGenerateConstants(t *testing.T) {
	r := &wiregen.Registry{
		Constants: []wiregen.WireConst{
			{TSName: "MSG_SCREEN", Value: 0},
			{TSName: "MSG_SCROLL", Value: 1},
			{TSName: "MODE_FLAG_BRACKETED_PASTE", Value: 0x01},
		},
	}
	out := r.GenerateConstants()

	if !strings.Contains(out, "// CODE-GENERATED by wiregen, DO NOT EDIT.") {
		t.Errorf("missing header comment, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MSG_SCREEN = 0;") {
		t.Errorf("missing MSG_SCREEN constant, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MSG_SCROLL = 1;") {
		t.Errorf("missing MSG_SCROLL constant, got:\n%s", out)
	}
	if !strings.Contains(out, "export const MODE_FLAG_BRACKETED_PASTE = 1;") {
		t.Errorf("missing MODE_FLAG_BRACKETED_PASTE constant, got:\n%s", out)
	}
}

func TestGenerateConstants_Empty(t *testing.T) {
	r := newRegistry()
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	// constants.gen.ts should NOT be written when Constants is nil
	_, err := os.Stat(dir + "/constants.gen.ts")
	if !os.IsNotExist(err) {
		t.Errorf("expected constants.gen.ts to not exist when Constants is empty, but it does")
	}
}

func TestGenerateRegistry_SelfContained(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithSelfContainedRegistry(true),
	)
	r.WireTypes = []reflect.Type{
		reflect.TypeFor[Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	out := r.GenerateRegistry()

	if !strings.Contains(out, "new Map<string, Decoder<unknown>>()") {
		t.Errorf("missing Map declaration, got:\n%s", out)
	}
	if !strings.Contains(out, "registry.set(") {
		t.Errorf("missing registry.set call, got:\n%s", out)
	}
	if !strings.Contains(out, "getSSEDecoder") {
		t.Errorf("missing getSSEDecoder function, got:\n%s", out)
	}
	if strings.Contains(out, "import { registerSSEDecoder }") {
		t.Errorf("should NOT contain registerSSEDecoder import in self-contained mode, got:\n%s", out)
	}
}

func TestGenerate_SelfContained_NoBusImport(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./test-validators.js"),
		wiregen.WithSelfContainedRegistry(true),
	)
	r.WireTypes = []reflect.Type{
		reflect.TypeFor[Notification](),
	}
	r.SSEEvents = []wiregen.SSERegEntry{
		{EventType: "notification", TypeName: "Notification"},
	}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate should succeed with SelfContainedRegistry=true and empty BusImport, got: %v", err)
	}
}

func TestPanicOnEmptyValidatorsImport(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes: []reflect.Type{
			reflect.TypeFor[Notification](),
		},
		ValidatorsImport: "", // must panic
	}
	defer func() {
		rec := recover()
		if rec == nil {
			t.Fatal("expected panic when ValidatorsImport is empty, but did not panic")
		}
		msg, ok := rec.(string)
		if !ok || !strings.Contains(msg, "ValidatorsImport must be set") {
			t.Fatalf("unexpected panic message: %v", rec)
		}
	}()
	r.GenerateDecoders()
}

func TestPanicOnEmptyBusImport(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes: []reflect.Type{
			reflect.TypeFor[Notification](),
		},
		SSEEvents: []wiregen.SSERegEntry{
			{EventType: "notification", TypeName: "Notification"},
		},
		ValidatorsImport:      "./test-validators.js",
		BusImport:             "", // must panic when SelfContainedRegistry is false
		SelfContainedRegistry: false,
	}
	defer func() {
		rec := recover()
		if rec == nil {
			t.Fatal("expected panic when BusImport is empty, but did not panic")
		}
		msg, ok := rec.(string)
		if !ok || !strings.Contains(msg, "BusImport must be set") {
			t.Fatalf("unexpected panic message: %v", rec)
		}
	}()
	r.GenerateRegistry()
}

// --- New feature tests ---

func TestUnexportedFieldsSkipped(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[HasUnexported]()},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  name: string;") {
		t.Errorf("exported field 'name' should be present, got:\n%s", out)
	}
	if strings.Contains(out, "internal") || strings.Contains(out, "hidden") {
		t.Errorf("unexported fields should NOT appear in output, got:\n%s", out)
	}
}

func TestByteSliceToString(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[HasBytes]()},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  data: string;") {
		t.Errorf("[]byte should map to string, got:\n%s", out)
	}
	if strings.Contains(out, "number[]") {
		t.Errorf("[]byte should NOT map to number[], got:\n%s", out)
	}
	// Decoder should use reqStr
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "reqStr(o, \"data\"") {
		t.Errorf("[]byte decoder should use reqStr, got:\n%s", dec)
	}
}

func TestOmitzeroMakesOptional(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[HasOmitzero]()},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  value?: string;") {
		t.Errorf("omitzero field should be optional, got:\n%s", out)
	}
	if !strings.Contains(out, "  name: string;") {
		t.Errorf("non-omitzero field should be required, got:\n%s", out)
	}
}

func TestJSONStringTag(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[HasJSONString]()},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  big_id: string;") {
		t.Errorf("json:\",string\" field should be typed as string, got:\n%s", out)
	}
	// Decoder should use reqStr for the string-wrapped field
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "reqStr(o, \"big_id\"") {
		t.Errorf("json:\",string\" decoder should use reqStr, got:\n%s", dec)
	}
}

func TestDecoderMappings(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[HasCustomMapped]()},
		TypeMappings:     map[reflect.Type]string{reflect.TypeFor[CustomID](): "string"},
		DecoderMappings:  map[reflect.Type]string{reflect.TypeFor[CustomID](): "reqStr"},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	out := r.GenerateTypes()
	if !strings.Contains(out, "  id: string;") {
		t.Errorf("TypeMappings should map CustomID to string, got:\n%s", out)
	}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, "reqStr(o, \"id\"") {
		t.Errorf("DecoderMappings should use reqStr for CustomID, got:\n%s", dec)
	}
}

func TestTypeMappingsWithoutDecoder(t *testing.T) {
	r := &wiregen.Registry{
		WireTypes:        []reflect.Type{reflect.TypeFor[HasCustomMapped]()},
		TypeMappings:     map[reflect.Type]string{reflect.TypeFor[CustomID](): "string"},
		ValidatorsImport: "./v.js",
		BusImport:        "./b.js",
	}
	dec := r.GenerateDecoders()
	// Without DecoderMappings, should fall back to `as string` cast
	if !strings.Contains(dec, "o[\"id\"] as string") {
		t.Errorf("TypeMappings without DecoderMappings should cast, got:\n%s", dec)
	}
}

func TestTypesImportPath(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithTypesImportPath("../shared/types.gen.js"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[User]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	dec := r.GenerateDecoders()
	if !strings.Contains(dec, `from "../shared/types.gen.js"`) {
		t.Errorf("should use custom TypesImportPath, got:\n%s", dec)
	}
	if strings.Contains(dec, `from "./types.gen.js"`) {
		t.Errorf("should NOT use default types import path, got:\n%s", dec)
	}
}

// ExampleRegistry_Generate demonstrates basic wiregen usage for go doc.
func ExampleRegistry_Generate() {
	type Role string
	type Person struct {
		Name string `json:"name"`
		Age  int    `json:"age"`
		Role Role   `json:"role"`
	}

	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./validators.js"),
		wiregen.WithBusImport("./bus.js"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Person]()}
	r.Enums = map[string]wiregen.EnumDef{"Role": {Values: []string{"admin", "user"}}}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "person", TypeName: "Person"}}

	fmt.Println(r.GenerateTypes())
	// Output:
	// // CODE-GENERATED by wiregen, DO NOT EDIT.
	//
	// export type Role = "admin" | "user";
	//
	// export interface Person {
	//   name: string;
	//   age: number;
	//   role: Role;
	// }
	//
}

func TestNewRegistry_Defaults(t *testing.T) {
	r := wiregen.NewRegistry()
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.Enums = map[string]wiregen.EnumDef{"Status": {Values: []string{"active"}}}
	// Zero-value defaults should be applied by init()
	out := r.GenerateTypes()
	if !strings.Contains(out, "// CODE-GENERATED by wiregen, DO NOT EDIT.") {
		t.Errorf("expected default header comment, got:\n%s", out)
	}
}

func TestNewRegistry_WithFilenames(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithFilenames("my_types.ts", "my_decoders.ts", "my_registry.ts", "my_consts.ts"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Address]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "addr", TypeName: "Address"}}
	r.Constants = []wiregen.WireConst{{TSName: "X", Value: 1}}
	dir := t.TempDir()
	if err := r.Generate(dir); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}
	for _, f := range []string{"my_types.ts", "my_decoders.ts", "my_registry.ts", "my_consts.ts"} {
		if _, err := os.Stat(dir + "/" + f); err != nil {
			t.Errorf("expected file %s to exist: %v", f, err)
		}
	}
}

func TestNewRegistry_WithRegistryFuncName(t *testing.T) {
	r := wiregen.NewRegistry(
		wiregen.WithValidatorsImport("./v.js"),
		wiregen.WithBusImport("./b.js"),
		wiregen.WithRegisterFuncName("myRegister"),
		wiregen.WithRegistryFuncName("initAll"),
	)
	r.WireTypes = []reflect.Type{reflect.TypeFor[Notification]()}
	r.SSEEvents = []wiregen.SSERegEntry{{EventType: "notif", TypeName: "Notification"}}
	out := r.GenerateRegistry()
	if !strings.Contains(out, "myRegister") {
		t.Errorf("expected custom register func name, got:\n%s", out)
	}
	if !strings.Contains(out, "export function initAll()") {
		t.Errorf("expected custom registry func name, got:\n%s", out)
	}
}
