// CODE-GENERATED by wiregen, DO NOT EDIT.

import fc from "fast-check";
import type { Address, CoverageEvent, CycleA, CycleB, EventData, HasBytes, HasCustomMapped, HasInterface, HasJSONString, HasMap, HasMappedSlice, HasRaw, HasTime, MapOfStructs, MapVal, NotifyEvent, Priority, ScanEvent, SelfMap, SelfMapRequired, SelfSlice, SelfSliceRequired, Status, User, WithEmbedding } from "./types.gen.js";

// A map key is never the string "__proto__". JSON.parse materializes such a key
// as an own property, while the generated decodeRecord assigns out[k], and
// out["__proto__"] sets the prototype instead of adding a key — so the entry
// would vanish from the decoded value and no round trip could hold.
const arbMapKey: fc.Arbitrary<string> = fc.string().filter((k) => k !== "__proto__");

export const arbPriority: fc.Arbitrary<Priority> = fc.constantFrom("low", "medium", "high", "critical");
export const arbStatus: fc.Arbitrary<Status> = fc.constantFrom("active", "inactive", "banned");

const arbModel = fc.letrec<{
  Address: Address;
  CoverageEvent: CoverageEvent;
  CycleA: CycleA;
  CycleB: CycleB;
  EventData: EventData;
  HasBytes: HasBytes;
  HasCustomMapped: HasCustomMapped;
  HasInterface: HasInterface;
  HasJSONString: HasJSONString;
  HasMap: HasMap;
  HasMappedSlice: HasMappedSlice;
  HasRaw: HasRaw;
  HasTime: HasTime;
  MapOfStructs: MapOfStructs;
  MapVal: MapVal;
  NotifyEvent: NotifyEvent;
  ScanEvent: ScanEvent;
  SelfMap: SelfMap;
  SelfMapRequired: SelfMapRequired;
  SelfSlice: SelfSlice;
  SelfSliceRequired: SelfSliceRequired;
  User: User;
  WithEmbedding: WithEmbedding;
}>((tie) => ({
  Address: fc.record(
    {
      street: fc.string(),
      city: fc.string(),
      zip: fc.string(),
    },
    { requiredKeys: ["street", "city"] },
  ),
  CoverageEvent: fc.record(
    {
      media_id: fc.string(),
      language: fc.string(),
    },
    { requiredKeys: ["media_id", "language"] },
  ),
  CycleA: fc.oneof(
    { maxDepth: 5, depthIdentifier: "wiregen" },
    fc.record(
      {
        name: fc.string(),
      },
      { requiredKeys: ["name"] },
    ),
    fc.record(
      {
        name: fc.string(),
        b: tie("CycleB"),
      },
      { requiredKeys: ["name"] },
    ),
  ),
  CycleB: fc.oneof(
    { maxDepth: 5, depthIdentifier: "wiregen" },
    fc.record(
      {
        value: fc.string(),
      },
      { requiredKeys: ["value"] },
    ),
    fc.record(
      {
        value: fc.string(),
        a: tie("CycleA"),
      },
      { requiredKeys: ["value"] },
    ),
  ),
  EventData: fc.oneof(tie("CoverageEvent"), tie("NotifyEvent"), tie("ScanEvent")),
  HasBytes: fc.record(
    {
      data: fc.base64String(),
      name: fc.string(),
    },
    { requiredKeys: ["data", "name"] },
  ),
  HasCustomMapped: fc.record(
    {
      // opaque: github.com/cplieger/wiregen/v3/testdata/basic.CustomID is consumer-mapped, so its shape is not in wiregen's model
      id: fc.jsonValue().filter((v) => v !== null) as unknown as fc.Arbitrary<Record<string, string>>,
      name: fc.string(),
    },
    { requiredKeys: ["id", "name"] },
  ),
  HasInterface: fc.record(
    {
      payload: fc.jsonValue(),
      name: fc.string(),
    },
    { requiredKeys: ["payload", "name"] },
  ),
  HasJSONString: fc.record(
    {
      big_id: fc.string(),
      name: fc.string(),
    },
    { requiredKeys: ["big_id", "name"] },
  ),
  HasMap: fc.record(
    {
      meta: fc.dictionary(arbMapKey, fc.string(), { maxKeys: 2, size: "small", depthIdentifier: "wiregen" }),
      name: fc.string(),
    },
    { requiredKeys: ["meta", "name"] },
  ),
  HasMappedSlice: fc.record(
    {
      ids: fc.array(fc.jsonValue().filter((v) => v !== null) as unknown as fc.Arbitrary<Record<string, string>>, { maxLength: 2, size: "small", depthIdentifier: "wiregen" }),
      name: fc.string(),
    },
    { requiredKeys: ["ids", "name"] },
  ),
  HasRaw: fc.record(
    {
      data: fc.jsonValue(),
      name: fc.string(),
    },
    { requiredKeys: ["data", "name"] },
  ),
  HasTime: fc.record(
    {
      created: fc.string(),
      updated: fc.string(),
    },
    { requiredKeys: ["created"] },
  ),
  MapOfStructs: fc.record(
    {
      data: fc.dictionary(arbMapKey, tie("MapVal"), { maxKeys: 2, size: "small", depthIdentifier: "wiregen" }),
    },
    { requiredKeys: ["data"] },
  ),
  MapVal: fc.record(
    {
      x: fc.double({ noNaN: true, noDefaultInfinity: true }),
    },
    { requiredKeys: ["x"] },
  ),
  NotifyEvent: fc.record(
    {
      level: fc.string(),
      text: fc.string(),
    },
    { requiredKeys: ["level", "text"] },
  ),
  ScanEvent: fc.record(
    {
      action: fc.string(),
      succeeded: fc.boolean(),
    },
    { requiredKeys: ["action"] },
  ),
  SelfMap: fc.oneof(
    { maxDepth: 5, depthIdentifier: "wiregen" },
    fc.record(
      {
        name: fc.string(),
      },
      { requiredKeys: ["name"] },
    ),
    fc.record(
      {
        name: fc.string(),
        children: fc.dictionary(arbMapKey, tie("SelfMap"), { maxKeys: 2, size: "small", depthIdentifier: "wiregen" }),
      },
      { requiredKeys: ["name"] },
    ),
  ),
  SelfMapRequired: fc.oneof(
    { maxDepth: 5, depthIdentifier: "wiregen" },
    fc.record(
      {
        name: fc.string(),
        children: fc.constant<Record<string, SelfMapRequired>>({}),
      },
      { requiredKeys: ["name", "children"] },
    ),
    fc.record(
      {
        name: fc.string(),
        children: fc.dictionary(arbMapKey, tie("SelfMapRequired"), { maxKeys: 2, size: "small", depthIdentifier: "wiregen" }),
      },
      { requiredKeys: ["name", "children"] },
    ),
  ),
  SelfSlice: fc.oneof(
    { maxDepth: 5, depthIdentifier: "wiregen" },
    fc.record(
      {
        name: fc.string(),
      },
      { requiredKeys: ["name"] },
    ),
    fc.record(
      {
        name: fc.string(),
        children: fc.array(tie("SelfSlice"), { maxLength: 2, size: "small", depthIdentifier: "wiregen" }),
      },
      { requiredKeys: ["name"] },
    ),
  ),
  SelfSliceRequired: fc.oneof(
    { maxDepth: 5, depthIdentifier: "wiregen" },
    fc.record(
      {
        name: fc.string(),
        children: fc.constant<SelfSliceRequired[]>([]),
      },
      { requiredKeys: ["name", "children"] },
    ),
    fc.record(
      {
        name: fc.string(),
        children: fc.array(tie("SelfSliceRequired"), { maxLength: 2, size: "small", depthIdentifier: "wiregen" }),
      },
      { requiredKeys: ["name", "children"] },
    ),
  ),
  User: fc.record(
    {
      age: fc.double({ noNaN: true, noDefaultInfinity: true }),
      address: tie("Address"),
      name: fc.string(),
      email: fc.string(),
      status: arbStatus,
      tags: fc.array(fc.string(), { maxLength: 2, size: "small", depthIdentifier: "wiregen" }),
      id: fc.double({ noNaN: true, noDefaultInfinity: true }),
    },
    { requiredKeys: ["address", "name", "status", "id"] },
  ),
  WithEmbedding: fc.record(
    {
      id: fc.double({ noNaN: true, noDefaultInfinity: true }),
      created_at: fc.string(),
      name: fc.string(),
    },
    { requiredKeys: ["id", "created_at", "name"] },
  ),
}));

export const arbAddress: fc.Arbitrary<Address> = arbModel.Address;
export const arbCoverageEvent: fc.Arbitrary<CoverageEvent> = arbModel.CoverageEvent;
export const arbCycleA: fc.Arbitrary<CycleA> = arbModel.CycleA;
export const arbCycleB: fc.Arbitrary<CycleB> = arbModel.CycleB;
export const arbEventData: fc.Arbitrary<EventData> = arbModel.EventData;
export const arbHasBytes: fc.Arbitrary<HasBytes> = arbModel.HasBytes;
export const arbHasCustomMapped: fc.Arbitrary<HasCustomMapped> = arbModel.HasCustomMapped;
export const arbHasInterface: fc.Arbitrary<HasInterface> = arbModel.HasInterface;
export const arbHasJSONString: fc.Arbitrary<HasJSONString> = arbModel.HasJSONString;
export const arbHasMap: fc.Arbitrary<HasMap> = arbModel.HasMap;
export const arbHasMappedSlice: fc.Arbitrary<HasMappedSlice> = arbModel.HasMappedSlice;
export const arbHasRaw: fc.Arbitrary<HasRaw> = arbModel.HasRaw;
export const arbHasTime: fc.Arbitrary<HasTime> = arbModel.HasTime;
export const arbMapOfStructs: fc.Arbitrary<MapOfStructs> = arbModel.MapOfStructs;
export const arbMapVal: fc.Arbitrary<MapVal> = arbModel.MapVal;
export const arbNotifyEvent: fc.Arbitrary<NotifyEvent> = arbModel.NotifyEvent;
export const arbScanEvent: fc.Arbitrary<ScanEvent> = arbModel.ScanEvent;
export const arbSelfMap: fc.Arbitrary<SelfMap> = arbModel.SelfMap;
export const arbSelfMapRequired: fc.Arbitrary<SelfMapRequired> = arbModel.SelfMapRequired;
export const arbSelfSlice: fc.Arbitrary<SelfSlice> = arbModel.SelfSlice;
export const arbSelfSliceRequired: fc.Arbitrary<SelfSliceRequired> = arbModel.SelfSliceRequired;
export const arbUser: fc.Arbitrary<User> = arbModel.User;
export const arbWithEmbedding: fc.Arbitrary<WithEmbedding> = arbModel.WithEmbedding;

export const ARBITRARY_BY_TYPE: Record<string, fc.Arbitrary<unknown>> = {
  Address: arbAddress,
  CoverageEvent: arbCoverageEvent,
  CycleA: arbCycleA,
  CycleB: arbCycleB,
  EventData: arbEventData,
  HasBytes: arbHasBytes,
  HasCustomMapped: arbHasCustomMapped,
  HasInterface: arbHasInterface,
  HasJSONString: arbHasJSONString,
  HasMap: arbHasMap,
  HasMappedSlice: arbHasMappedSlice,
  HasRaw: arbHasRaw,
  HasTime: arbHasTime,
  MapOfStructs: arbMapOfStructs,
  MapVal: arbMapVal,
  NotifyEvent: arbNotifyEvent,
  Priority: arbPriority,
  ScanEvent: arbScanEvent,
  SelfMap: arbSelfMap,
  SelfMapRequired: arbSelfMapRequired,
  SelfSlice: arbSelfSlice,
  SelfSliceRequired: arbSelfSliceRequired,
  Status: arbStatus,
  User: arbUser,
  WithEmbedding: arbWithEmbedding,
};
