// CODE-GENERATED by wiregen, DO NOT EDIT.

import { asObject, reqStr, reqNum, optStr, optNum, reqOneOf, decodeArray, decodeRecord, type Decoder } from "./test-validators.js";
import type { Address, HasBytes, HasMap, HasTime, Notification, User, WithEmbedding } from "./types.gen.js";

const STATUSS = ["active", "inactive", "banned"] as const;

export const decodeAddress: Decoder<Address> = (v) => {
  const o = asObject(v, "$.address");
  const out: Address = {
    street: reqStr(o, "street", "$.address"),
    city: reqStr(o, "city", "$.address"),
  };
  const zip = optStr(o, "zip", "$.address");
  if (zip !== undefined) out.zip = zip;
  return out;
};

export const decodeHasBytes: Decoder<HasBytes> = (v) => {
  const o = asObject(v, "$.has_bytes");
  const out: HasBytes = {
    data: reqStr(o, "data", "$.has_bytes"),
    name: reqStr(o, "name", "$.has_bytes"),
  };
  return out;
};

export const decodeHasMap: Decoder<HasMap> = (v) => {
  const o = asObject(v, "$.has_map");
  const out: HasMap = {
    name: reqStr(o, "name", "$.has_map"),
  };
  if (o["meta"] !== undefined) out.meta = decodeRecord(o["meta"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.has_map.meta");
  return out;
};

export const decodeHasTime: Decoder<HasTime> = (v) => {
  const o = asObject(v, "$.has_time");
  const out: HasTime = {
    created: reqStr(o, "created", "$.has_time"),
  };
  const updated = optStr(o, "updated", "$.has_time");
  if (updated !== undefined) out.updated = updated;
  return out;
};

export const decodeNotification: Decoder<Notification> = (v) => {
  const o = asObject(v, "$.notification");
  const out: Notification = {
    kind: reqStr(o, "kind", "$.notification"),
    message: reqStr(o, "message", "$.notification"),
  };
  return out;
};

export const decodeUser: Decoder<User> = (v) => {
  const o = asObject(v, "$.user");
  const out: User = {
    address: decodeAddress(o["address"]),
    name: reqStr(o, "name", "$.user"),
    status: reqOneOf(o, "status", STATUSS, "$.user"),
    id: reqNum(o, "id", "$.user"),
  };
  const age = optNum(o, "age", "$.user");
  if (age !== undefined) out.age = age;
  const email = optStr(o, "email", "$.user");
  if (email !== undefined) out.email = email;
  if (o["tags"] !== undefined) out.tags = decodeArray(o["tags"], (v) => { if (typeof v !== "string") throw new TypeError("expected string"); return v as string; }, "$.user.tags");
  return out;
};

export const decodeWithEmbedding: Decoder<WithEmbedding> = (v) => {
  const o = asObject(v, "$.with_embedding");
  const out: WithEmbedding = {
    id: reqNum(o, "id", "$.with_embedding"),
    created_at: reqStr(o, "created_at", "$.with_embedding"),
    name: reqStr(o, "name", "$.with_embedding"),
  };
  return out;
};

