// CODE-GENERATED by wiregen, DO NOT EDIT.

export type Status = "active" | "inactive" | "banned";

/** Address represents a physical mailing address. */
export interface Address {
  street: string;
  city: string;
  zip?: string;
}

/** HasBytes has a []byte field that should map to string (base64). */
export interface HasBytes {
  data: string;
  name: string;
}

/** HasMap has a map field. */
export interface HasMap {
  meta?: Record<string, string>;
  name: string;
}

/** HasTime has a time.Time field. */
export interface HasTime {
  created: string;
  updated?: string;
}

/** Notification is the payload for toast notifications. */
export interface Notification {
  kind: string;
  message: string;
}

/** User represents a registered user in the system. */
export interface User {
  age?: number;
  address: Address;
  name: string;
  email?: string;
  status: Status;
  tags?: string[];
  id: number;
}

/** WithEmbedding embeds Base. */
export interface WithEmbedding {
  id: number;
  created_at: string;
  name: string;
}

