name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md", "LICENSE", ".gitignore"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/go-ci.yaml@49ec4be725bc5117be1181418964b0df22bd87d8 # v1
