name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: cplieger/ci/.github/workflows/go-ci.yaml@19357decce18d479bf83e80a8d78b67226dfaf24 # v1
