name: Release
on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: cplieger/ci/.github/workflows/release.yaml@38aa4e20293b20ff3f707553f46f54e287c97b5f # v1
    with:
      target: go
