name: Security

on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - Dockerfile
      - .github/workflows/security.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    uses: cplieger/ci/.github/workflows/security-scan.yaml@b7de6406a5e9bf1507fa335012f8550e9b296853 # v2
