name: Security

on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - Dockerfile
      - .github/workflows/security.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    uses: cplieger/ci/.github/workflows/security-scan.yaml@74f0e45b06212edba51f493bc133354e501b9f5a # v2
