name: Security

on:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - package.json
      - package-lock.json
      - Dockerfile
      - .github/workflows/security.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    uses: cplieger/ci/.github/workflows/security-scan.yaml@c301d8902fad90d897c9a3f22cb9cf3ee8cb5700 # v2
